### ISSUE TITLE
Update instructions for Erlang-Extraction Exercise

### ISSUE THREAD

**Issue by RickHPotter** [exercism/gleam#496]
https://exercism.org/tracks/gleam/exercises/erlang-extraction

In the exercise, it says

```plaintext
The function should take three arguments:

The GbTree to insert into.
The key to insert.
The value to insert.
```

But the correct order is as follows

[insert(Key, Value, Tree1)](https://www.erlang.org/doc/apps/stdlib/gb_trees.html#insert/3)
Inserts Key with value Value into Tree1 and returns the new tree. Assumes that the key is not present in the tree, crashes otherwise.

**Comment by RickHPotter** [comment]
I just realised that the `delete` external function is also with the wrong order. It should be `key, Tree1`, but the exercise says otherwise.

**Comment by Varpie** [comment]
I believe the order isn't the same as the Erlang version on purpose: having the tree as the first parameter is better for piping in Gleam, and the hints remind users that a private function can be used to change the order of parameters.
Since you created the issue,  #514 was also merged, which adds a reminder that the correct order of arguments should be used.

**Comment by lpil** [comment]
That's right 👍
